# Intro to Project
This is for a semester long project for an Introductory Machine Learning class CS07455.

The goal of the project is to get hands on experience with the entire practical machine learning process
from data exploration, cleaning, to modeling.

This is the Jupyter Notebook with all the code used for the project and some comments, but most of the details will be found in 
the final report

# Background

### Dataset
- This Dataset was obtained from Kaggle: [Melbourne Housing Snapshot](https://www.kaggle.com/datasets/dansbecker/melbourne-housing-snapshot/)
#### Context
- Melbourne real estate is BOOMING. Can you find the insight or predict the next big trend to become a real estate mogul… or even harder, to snap up a reasonably priced 2-bedroom unit?

#### Notes on Specific Variables
- Rooms: Number of rooms

- Price: Price in dollars

- Method: 
<br>S - property sold; 
<br>SP - property sold prior; 
<br>PI - property passed in; 
<br>PN - sold prior not disclosed;
<br> SN - sold not disclosed; 
<br>NB - no bid;
<br> VB - vendor bid; 
<br>W - withdrawn prior to auction; 
<br>SA - sold after auction;
<br>SS - sold after auction price not disclosed. 
<br>N/A - price or highest bid not available.

- Type: 
<br>br - bedroom(s); 
<br>h - house,cottage,villa, semi,terrace; 
<br>u - unit, duplex; 
<br>t - townhouse; dev site - development site; 
<br>o res - other residential.

- SellerG: Real Estate Agent

- Date: Date sold

- Distance: Distance from CBD (Central Business District)

- Regionname: General Region (West, North West, North, North east …etc)

- Propertycount: Number of properties that exist in the suburb.

- Bedroom2 : Scraped # of Bedrooms (from different source)

- Bathroom: Number of Bathrooms

- Car: Number of carspots

- Landsize: Land Size

- BuildingArea: Building Size

- CouncilArea: Governing council for the area

#### Business Goals
- We will be using and training on this dataset to be able to predict the price of Melbourne houses. This is a great initiative as being able to accurately predict 
the price of houses can be useful to many different applications. For example it can be used by customers or investors to find houses for cheap. Or it can be used 
by sellers to see at what price points they should sell houses so they can maximize their profit and selling potential. Investors can use the model to quickly 
evaluate possible investments and what will yeild them the highest return on Investment.

# Data Exploration

Before we begin actually using Machine Learning on the dataset it is vital we explore it to fully understand what we are working with.

To make this process much easier we can simply use Pandas Profiling which is a very powerful module that will automate a lot of the Data Analysis for us.

To see a detailed discussion on the insights from the report and the data exploration phase in general please refer to the final project report.

In [44]:
# Import Libraries and Raw Dataset
import pandas as pd
df = pd.read_csv('raw_data.csv')

### Pandas Profiling

In [4]:
# Use Pandas Profiling to accelerate the Data Exploration process
# Profiling Report has already been created (see attached) but you can uncomment and re-run the code below to generate the report again

#from pandas_profiling import ProfileReport
#profile = ProfileReport(df, tilte ='Melbourne Housing Raw Data Report')
#profile.to_file('RawDataReport.html')

### Explore Basic shape

In [2]:
df.shape # 21 features, 13580 rows

(13580, 21)

In [17]:
df.head(1)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0

### Explore Features

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

In [10]:
df.describe() # Describe all numerical columns

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [11]:
df.describe(include = ['O']) # Describe all non-numerical/categorical columns

,Suburb,Address,Type,Method,SellerG,Date,CouncilArea,Regionname
count,13580,13580,13580,13580,13580,13580,12211,13580
unique,314,13378,3,5,268,58,33,8
top,Reservoir,36 Aberfeldie St,h,S,Nelson,27/05/2017,Moreland,Southern Metropolitan
freq,359,3,9449,9022,1565,473,1163,4695

### Duplication

In [24]:
df.duplicated(subset=['Address']).sum()

202

In [27]:
df.query('Address == "36 Aberfeldie St"')

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
4125,Moonee Ponds,36 Aberfeldie St,3,h,1725000.0,PI,Nelson,24/09/2016,6.9,3039.0,...,2.0,3.0,596.0,203.0,1950.0,Moonee Valley,-37.76090,144.90500,Western Metropolitan,6232.0
9240,Moonee Ponds,36 Aberfeldie St,3,h,1850000.0,SP,McDonald,3/06/2017,6.2,3039.0,...,2.0,2.0,596.0,203.0,1950.0,Moonee Valley,-37.76086,144.90497,Western Metropolitan,6232.0
9634,Moonee Ponds,36 Aberfeldie St,3,h,1850000.0,SP,McDonald,17/06/2017,6.2,3039.0,...,2.0,2.0,596.0,203.0,1950.0,Moonee Valley,-37.76086,144.90497,Western Metropolitan,6232.0

In [28]:
df.query('Address == "4 Bell St"')

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
1364,Brunswick,4 Bell St,4,h,1790000.0,S,Ray,27/06/2016,5.2,3056.0,...,1.0,1.0,416.0,129.0,1920.0,Moreland,-37.77370,144.96500,Northern Metropolitan,11918.0
9702,Richmond,4 Bell St,2,h,1172000.0,S,Collins,17/06/2017,2.4,3121.0,...,1.0,0.0,155.0,NaN,NaN,Yarra,-37.82418,145.00185,Northern Metropolitan,14949.0

In [3]:
# Function to find discrepancies in addresses that have duplicates
def find_discrepancies(df, Address, features):
    # Group by the address column
    grouped = df.groupby(Address)

    # Iterate over each group
    for address, group in grouped:
        # Proceed only if there is more than one entry for the address
        if len(group) > 1:
            # Check if all entries are the same for the feature columns
            if not group[features].eq(group[features].iloc[0]).all().all():
                # If not, print the group with discrepancies
                print(f"Discrepancies found for address: {address}")
                print(group.to_string(index=False))
                print("\n")

# List of feature columns to check
excluded_columns = ['Price', 'Method', 'SellerG']
features = [col for col in df.columns.tolist() if col not in excluded_columns]

# Find discrepancies
find_discrepancies(df, 'Address', features)

Discrepancies found for address: 1 Bellarine St
 Suburb        Address  Rooms Type     Price Method       SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
Preston 1 Bellarine St      4    h 1400000.0     VB        Jellis 18/03/2017       8.8    3072.0       4.0       2.0  2.0     559.0         217.0     1925.0     Darebin  -37.73470   144.99660 Northern Metropolitan        14577.0
Preston 1 Bellarine St      5    h 1400000.0     PI hockingstuart  3/06/2017       8.4    3072.0       5.0       2.0  2.0     558.0         217.0     1925.0     Darebin  -37.73472   144.99658 Northern Metropolitan        14577.0


Discrepancies found for address: 1 Daisy St
  Suburb    Address  Rooms Type     Price Method SellerG      Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt   CouncilArea  Lattitude  Longtitude           Regionname  Propertycount
Essendon 1 Daisy St      4    h 1400000.0     VB  Nelson 8/04/2017       8.0    3040.0       4.0       2.0  1.0     267.0           NaN        NaN Moonee Valley  -37.75580   144.91060 Western Metropolitan         9264.0
Essendon 1 Daisy St      4    h 1360000.0      S  Jellis 3/06/2017       7.5    3040.0       4.0       2.0  1.0     267.0           NaN        NaN Moonee Valley  -37.75472   144.92723 Western Metropolitan         9264.0


Discrepancies found for address: 1/1 Clarendon St
   Suburb          Address  Rooms Type    Price Method SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude           Regionname  Propertycount
Maidstone 1/1 Clarendon St      3    t 675000.0      S  Biggin 22/04/2017       9.2    3012.0       3.0       2.0  2.0     159.0         128.0     2016.0 Maribyrnong  -37.78500   144.86730 Western Metropolitan         3873.0
Maidstone 1/1 Clarendon St      3    t 650000.0     PI     Jas  8/07/2017       6.4    3012.0       3.0       2.0  2.0     159.0         128.0     2016.0 Maribyrnong  -37.78502   144.86733 Western Metropolitan         3873.0
Maidstone 1/1 Clarendon St      3    t 670000.0     SP     Jas 29/07/2017       6.4    3012.0       3.0       2.0  2.0     159.0         128.0     2016.0 Maribyrnong  -37.78502   144.86733 Western Metropolitan         3873.0


Discrepancies found for address: 1/108 Truganini Rd
  Suburb            Address  Rooms Type     Price Method       SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
Carnegie 1/108 Truganini Rd      3    t  970000.0     PI      Marshall 14/05/2016      11.4    3163.0       3.0       2.0  2.0     325.0         223.0     2005.0   Glen Eira  -37.89330   145.05460 Southern Metropolitan         7822.0
Carnegie 1/108 Truganini Rd      4    t 1250000.0      S hockingstuart  8/07/2017      10.1    3163.0       4.0       3.0  2.0     326.0         223.0     2005.0   Glen Eira  -37.89334   145.05463 Southern Metropolitan         7822.0


Discrepancies found for address: 1/12 Hatfield Ct
        Suburb          Address  Rooms Type    Price Method SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude           Regionname  Propertycount
West Footscray 1/12 Hatfield Ct      6    u 520000.0     SP Sweeney  7/05/2016       8.2    3012.0       4.0       2.0  1.0       0.0         171.0     1970.0 Maribyrnong    -37.809    144.8686 Western Metropolitan         5058.0
West Footscray 1/12 Hatfield Ct      4    u 530000.0     SP Sweeney 10/09/2016       8.2    3012.0       4.0       2.0  1.0       0.0         171.0     1970.0 Maribyrnong    -37.809    144.8686 Western Metropolitan         5058.0


Discrepancies found for address: 1/16 Mawbey St
    Suburb        Address  Rooms Type    Price Method SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
Kensington 1/16 Mawbey St      2    u 420000.0     SP  Nelson  6/08/2016       4.2    3031.0       2.0       1.0  1.0       0.0          80.0     2002.0   Melbourne   -37.7899    144.9231 Northern Metropolitan         5263.0
Kensington 1/16 Mawbey St      2    u 395000.0     PI  Nelson 23/04/2016       4.2    3031.0       2.0       1.0  1.0       0.0          80.0     2002.0   Melbourne   -37.7899    144.9231 Northern Metropolitan         5263.0


Discrepancies found for address: 1/16 Osborne Av
   Suburb         Address  Rooms Type    Price Method       SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
Glen Iris 1/16 Osborne Av      2    t 965000.0      S hockingstuart  9/09/2017       7.3    3146.0       2.0       2.0  1.0     704.0           NaN        NaN         NaN  -37.85698   145.04686 Southern Metropolitan        10412.0
Glen Iris 1/16 Osborne Av      2    t 965000.0      S hockingstuart 16/09/2017       7.3    3146.0       2.0       2.0  1.0     704.0           NaN        NaN         NaN  -37.85698   145.04686 Southern Metropolitan        10412.0


Discrepancies found for address: 1/26 York St
 Suburb      Address  Rooms Type    Price Method SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
Glenroy 1/26 York St      3    t 600000.0     VB  Nelson 27/11/2016      13.0    3046.0       3.0       1.0  2.0     258.0         143.0     2001.0    Moreland   -37.7047    144.9087 Northern Metropolitan         8870.0
Glenroy 1/26 York St      3    t 595000.0     SP  Nelson 20/05/2017      13.0    3046.0       3.0       1.0  2.0     258.0         142.6     2001.0    Moreland   -37.7047    144.9087 Northern Metropolitan         8870.0


Discrepancies found for address: 1/44 Arthur St
Suburb        Address  Rooms Type    Price Method    SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude           Regionname  Propertycount
Eltham 1/44 Arthur St      2    u 540000.0     VB Buckingham 15/07/2017      18.0    3095.0       2.0       1.0  1.0     132.0           NaN        NaN   Nillumbik  -37.71513   145.15324 Eastern Metropolitan         6990.0
Eltham 1/44 Arthur St      2    u 566000.0      S Buckingham  9/09/2017      18.0    3095.0       2.0       1.0  1.0     845.0           NaN        NaN         NaN  -37.71513   145.15324 Eastern Metropolitan         6990.0


Discrepancies found for address: 10 Beryl St
       Suburb     Address  Rooms Type     Price Method SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt   CouncilArea  Lattitude  Longtitude           Regionname  Propertycount
Essendon West 10 Beryl St      3    h 1245000.0      S    Brad  7/05/2016       9.8    3040.0       3.0       1.0  1.0      64.0           NaN        NaN Moonee Valley  -37.74940   144.88480 Western Metropolitan          588.0
Essendon West 10 Beryl St      3    h 1390000.0      S  Nelson 24/06/2017       7.5    3040.0       3.0       1.0  2.0     793.0           NaN        NaN Moonee Valley  -37.74944   144.88479 Western Metropolitan          588.0


Discrepancies found for address: 10/2 Howlett St
    Suburb         Address  Rooms Type    Price Method SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
Kensington 10/2 Howlett St      2    u 410000.0     PI Rendina 27/06/2016       4.2    3031.0       2.0       1.0  1.0       0.0          86.0     2000.0   Melbourne   -37.7897    144.9228 Northern Metropolitan         5263.0
Kensington 10/2 Howlett St      2    u 500000.0      S  Edward  8/04/2017       4.2    3031.0       2.0       1.0  1.0       0.0          86.0     2000.0   Melbourne   -37.7897    144.9228 Northern Metropolitan         5263.0


Discrepancies found for address: 101 The Fairway
   Suburb         Address  Rooms Type    Price Method      SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
Kingsbury 101 The Fairway      4    h 610000.0      S          Ray 12/11/2016      12.4    3083.0       4.0       1.0  1.0     465.0         120.0     1970.0     Darebin   -37.7126   145.03000 Northern Metropolitan         1414.0
Kingsbury 101 The Fairway      4    h 800001.0     SP Purplebricks  3/06/2017      12.1    3083.0       4.0       1.0  2.0     467.0         120.0     1970.0     Darebin   -37.7126   145.02996 Northern Metropolitan         1414.0


Discrepancies found for address: 103 Pleasant Rd
       Suburb         Address  Rooms Type     Price Method SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
Hawthorn East 103 Pleasant Rd      5    h 1900000.0     VB     Kay 28/05/2016       7.5    3123.0       3.0       3.0  3.0       0.0           NaN        NaN  Boroondara   -37.8351   145.05540 Southern Metropolitan         6482.0
Hawthorn East 103 Pleasant Rd      6    h 2200000.0     VB  Jellis 17/06/2017       6.2    3123.0       6.0       3.0  3.0     622.0           NaN        NaN  Boroondara   -37.8351   145.05542 Southern Metropolitan         6482.0


Discrepancies found for address: 11 Church St
        Suburb      Address  Rooms Type     Price Method SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
        Toorak 11 Church St      3    t 2700000.0     VB     Kay 12/06/2016       4.6    3142.0       3.0       2.0  2.0     294.0         220.0     2010.0 Stonnington  -37.85030   145.02920 Southern Metropolitan         7217.0
West Footscray 11 Church St      3    h 1100500.0      S     Jas 19/08/2017       6.4    3012.0       3.0       2.0  2.0     427.0         119.0     1936.0         NaN  -37.79105   144.87914  Western Metropolitan         5058.0


Discrepancies found for address: 11 Duffy St
        Suburb     Address  Rooms Type     Price Method SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt   CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
Essendon North 11 Duffy St      3    h 1320000.0      S    Brad 14/05/2016       9.4    3041.0       3.0       1.0  1.0     766.0           NaN        NaN Moonee Valley   -37.7388   144.90060  Western Metropolitan         1308.0
     Reservoir 11 Duffy St      3    h  680000.0     VB  Nelson 23/09/2017      12.0    3073.0       3.0       1.0  1.0     237.0           NaN        NaN           NaN   -37.7104   145.00717 Northern Metropolitan        21650.0


Discrepancies found for address: 11 Kerferd St
 Suburb       Address  Rooms Type     Price Method SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
Hampton 11 Kerferd St      3    h 1610000.0      S    Nick 18/06/2016      13.7    3188.0       3.0       1.0  2.0     569.0           NaN        NaN     Bayside   -37.9419    145.0100 Southern Metropolitan         5454.0
 Coburg 11 Kerferd St      2    h  941000.0      S  Nelson 13/05/2017       7.8    3058.0       2.0       1.0  2.0     413.0           NaN        NaN    Moreland   -37.7355    144.9545 Northern Metropolitan        11204.0


Discrepancies found for address: 11 Murphy St
  Suburb      Address  Rooms Type    Price Method SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
Oak Park 11 Murphy St      4    h 920000.0      S     Ray  7/11/2016      11.5    3046.0       4.0       2.0  2.0     780.0         179.0     1965.0    Moreland   -37.7168    144.9171 Northern Metropolitan         2651.0
 Preston 11 Murphy St      3    h 801000.0      S  Nelson 22/04/2017       8.8    3072.0       3.0       1.0  2.0     620.0           NaN        NaN     Darebin   -37.7305    144.9856 Northern Metropolitan        14577.0


Discrepancies found for address: 11 Nottingham St
    Suburb          Address  Rooms Type     Price Method SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
Kensington 11 Nottingham St      5    h 1710000.0     PI  Nelson 10/09/2016       4.2    3031.0       5.0       2.0  2.0     566.0         270.0     1890.0   Melbourne   -37.7893     144.933 Northern Metropolitan         5263.0
Kensington 11 Nottingham St      5    h 1900000.0     VB  Nelson 16/04/2016       4.2    3031.0       5.0       2.0  2.0     566.0         270.0     1890.0   Melbourne   -37.7893     144.933 Northern Metropolitan         5263.0


Discrepancies found for address: 11 Vincent St
   Suburb       Address  Rooms Type     Price Method SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
   Coburg 11 Vincent St      3    h  951000.0     SP  Nelson 27/11/2016       7.8    3058.0       3.0       2.0  0.0     342.0           NaN        NaN    Moreland   -37.7430    144.9560 Northern Metropolitan        11204.0
Glen Iris 11 Vincent St      4    h 3400000.0     VB     Kay  3/09/2016       9.2    3146.0       4.0       3.0  2.0     856.0         265.0     1920.0 Stonnington   -37.8628    145.0436 Southern Metropolitan        10412.0


Discrepancies found for address: 11 Wilson St
   Suburb      Address  Rooms Type     Price Method SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
Bentleigh 11 Wilson St      4    h 2520000.0     PI  Buxton 22/08/2016      13.0    3204.0       4.0       4.0  2.0     579.0         361.0     2012.0   Glen Eira   -37.9155    145.0243 Southern Metropolitan         6795.0
Bentleigh 11 Wilson St      4    h 2620000.0      S  Buxton 28/08/2016      13.0    3204.0       4.0       4.0  2.0     579.0         361.0     2012.0   Glen Eira   -37.9155    145.0243 Southern Metropolitan         6795.0


Discrepancies found for address: 112 Belmore Rd
Suburb        Address  Rooms Type     Price Method SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
Balwyn 112 Belmore Rd      5    h 2570000.0     PI      RT  3/12/2016       9.7    3103.0       5.0       3.0  2.0     715.0         420.0     2009.0  Boroondara   -37.8028    145.0768 Southern Metropolitan         5682.0
Balwyn 112 Belmore Rd      5    h 3020000.0     PI  Jellis 28/05/2016       9.7    3103.0       5.0       3.0  2.0     715.0         420.0     2009.0  Boroondara   -37.8028    145.0768 Southern Metropolitan         5682.0


Discrepancies found for address: 118 Westgarth St
   Suburb          Address  Rooms Type     Price Method SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
Northcote 118 Westgarth St      3    h 1500000.0     PI  Jellis 30/07/2016       5.5    3070.0       4.0       1.0  8.0     727.0           NaN     1900.0     Darebin   -37.7825    145.0072 Northern Metropolitan        11364.0
Northcote 118 Westgarth St      4    h 1822000.0      S  Nelson 13/05/2017       5.5    3070.0       4.0       1.0  8.0     728.0           NaN     1900.0     Darebin   -37.7825    145.0072 Northern Metropolitan        11364.0


Discrepancies found for address: 119 Park St
         Suburb     Address  Rooms Type     Price Method SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt   CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
South Melbourne 119 Park St      2    u  600000.0      S    Greg 12/11/2016       2.1    3205.0       2.0       1.0  1.0       0.0           NaN        NaN  Port Phillip   -37.8340    144.9665 Southern Metropolitan         5943.0
   Moonee Ponds 119 Park St      5    h 2300000.0     PI  Nelson 13/05/2017       6.9    3039.0       5.0       2.0  2.0     597.0         322.0     1930.0 Moonee Valley   -37.7611    144.9095  Western Metropolitan         6232.0


Discrepancies found for address: 12 Gordon St
 Suburb      Address  Rooms Type     Price Method       SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
 Coburg 12 Gordon St      4    h  865000.0      S          Brad 16/04/2016       7.8    3058.0       4.0       1.0  1.0     452.0         125.0     1925.0    Moreland   -37.7525    144.9480 Northern Metropolitan        11204.0
Newport 12 Gordon St      3    h 1040000.0      S hockingstuart 27/11/2016       8.4    3015.0       3.0       1.0  2.0     595.0           NaN        NaN Hobsons Bay   -37.8394    144.8669  Western Metropolitan         5498.0


Discrepancies found for address: 12 John St
        Suburb    Address  Rooms Type     Price Method SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt   CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
Bentleigh East 12 John St      4    h 1306000.0      S  Buxton 30/07/2016      13.9    3165.0       3.0       2.0  1.0     651.0           NaN        NaN     Glen Eira   -37.9190    145.0558 Southern Metropolitan        10969.0
    Flemington 12 John St      2    h  845000.0      S  Nelson 18/03/2017       4.4    3031.0       2.0       1.0  1.0       0.0           NaN     1910.0 Moonee Valley   -37.7838    144.9273 Northern Metropolitan         3593.0


Discrepancies found for address: 12 Witchwood Cl
     Suburb         Address  Rooms Type     Price Method       SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude            Regionname  Propertycount
South Yarra 12 Witchwood Cl      3    t 1460000.0     PI hockingstuart  4/06/2016       3.3    3141.0       2.0       2.0  1.0     181.0         148.0     1990.0   Melbourne   -37.8334    144.9867 Southern Metropolitan        14887.0
South Yarra 12 Witchwood Cl      3    h 1700000.0     SP        Biggin 28/08/2016       3.3    3141.0       2.0       2.0  1.0     181.0         148.0     1990.0   Melbourne   -37.8334    144.9867 Southern Metropolitan        14887.0


Discrepancies found for address: 122 Stephen St
    Suburb        Address  Rooms Type    Price Method       SellerG       Date  Distance  Postcode  Bedroom2  Bathroom  Car  Landsize  BuildingArea  YearBuilt CouncilArea  Lattitude  Longtitude           Regionname  Propertycount
Yarraville 122 Stephen St      1    u 510000.0     SP hockingstuart 11/02/2017       7.0    3013.0       1.0       1.0  2.0       0.0          83.0     2004.0 Maribyrnong   -37.8173     144.894 Western Metropolitan         6543.0
Yarraville 122 Stephen St      1    h 470000.0     PI           Jas 12/11/2016       7.0    3013.0       1.0       1.0  2.0       0.0          83.0     2004.0 Maribyrnong   -37.8173     144.894 Western Metropolitan         6543.0


Discrepancies found for address: 13 George St

### Correlations

No code here. See report.

### Categorical Variables relation to Price

In [37]:
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 350)

In [38]:
df[["CouncilArea", "Suburb"]].drop_duplicates().head(20)

        CouncilArea            Suburb
0             Yarra        Abbotsford
38    Moonee Valley      Airport West
78     Port Phillip       Albert Park
120         Darebin        Alphington
121           Yarra        Alphington
141     Hobsons Bay            Altona
186     Hobsons Bay      Altona North
221     Stonnington          Armadale
283   Moonee Valley        Ascot Vale
370      Boroondara         Ashburton
408          Monash           Ashwood
439   Moonee Valley  Avondale Heights
489    Port Phillip         Balaclava
506      Boroondara            Balwyn
585      Boroondara      Balwyn North
694       Glen Eira         Bentleigh
787       Glen Eira    Bentleigh East
969      Whitehorse          Box Hill
1010    Maribyrnong         Braybrook
1040        Bayside          Brighton

#### Descriptive Statistics of Price per categorical feature
"Type" of house especially shows a very strong indication. Other features also have some indication, whereas "Method" does not.

In [39]:
grouped_data = df.groupby('Regionname')['Price'].agg(['mean', 'median', 'std', 'count', 'var'])
print(grouped_data)

                                    mean     median            std  count           var
Regionname
Eastern Metropolitan        1.104080e+06  1010000.0  467417.860272   1471  2.184795e+11
Eastern Victoria            6.999808e+05   670000.0  165498.190135     53  2.738965e+10
Northern Metropolitan       8.981711e+05   806250.0  443967.693818   3890  1.971073e+11
Northern Victoria           5.948293e+05   540000.0  217761.670461     41  4.742015e+10
South-Eastern Metropolitan  9.229438e+05   850000.0  506525.336100    450  2.565679e+11
Southern Metropolitan       1.372963e+06  1250000.0  822529.158614   4695  6.765542e+11
Western Metropolitan        8.664205e+05   793000.0  394144.700287   2948  1.553500e+11
Western Victoria            3.975234e+05   400000.0   86211.956532     32  7.432501e+09

In [43]:
grouped_data = df.groupby('CouncilArea')['Price'].agg(['mean', 'median', 'std', 'count', 'var'])
print(grouped_data.head(10))

                           mean     median            std  count           var
CouncilArea
Banyule            9.444280e+05   802500.0  478687.885021    594  2.291421e+11
Bayside            1.652168e+06  1550000.0  792107.622046    489  6.274345e+11
Boroondara         1.647217e+06  1617500.0  923339.537548   1160  8.525559e+11
Brimbank           6.472007e+05   635400.0  154548.273134    424  2.388517e+10
Cardinia           5.731250e+05   601250.0  105863.372190      8  1.120705e+10
Casey              6.564079e+05   626250.0  165065.091799     38  2.724648e+10
Darebin            9.158000e+05   851000.0  452518.994126    934  2.047734e+11
Frankston          6.589849e+05   640000.0  188087.313044     53  3.537684e+10
Glen Eira          1.069279e+06  1040500.0  481916.074309    848  2.322431e+11
Greater Dandenong  6.970673e+05   683000.0  173325.971625     52  3.004189e+10

In [32]:
grouped_data = df.groupby('Type')['Price'].agg(['mean', 'median', 'std', 'count', 'var'])
print(grouped_data)

              mean     median            std  count           var
Type
h     1.242665e+06  1080000.0  668078.742092   9449  4.463292e+11
t     9.337351e+05   846750.0  395038.245773   1114  1.560552e+11
u     6.051275e+05   560000.0  260987.452871   3017  6.811445e+10

In [41]:
grouped_data = df.groupby('Method')['Price'].agg(['mean', 'median', 'std', 'count', 'var'])
print(grouped_data)

                mean    median            std  count           var
Method
PI      1.133242e+06  932500.0  730999.729516   1564  5.343606e+11
S       1.087327e+06  925000.0  613785.634739   9022  3.767328e+11
SA      1.025772e+06  872500.0  547952.730240     92  3.002522e+11
SP      8.998924e+05  770000.0  509987.899525   1703  2.600877e+11
VB      1.166510e+06  940000.0  805411.614931   1199  6.486879e+11

### Missing Values

In [42]:
missing_proportions = df.isnull().sum() / df.shape[0]
missing_proportions = missing_proportions * 100
print(missing_proportions[missing_proportions > 0])

Car              0.456554
BuildingArea    47.496318
YearBuilt       39.580265
CouncilArea     10.081001
dtype: float64

### Outliers

No code here. See report.

# Data Cleaning

### Remove unneeded features

In [45]:
# Removal of features that were decided to be removed in Data Exploration Phase
df = df.drop(['Suburb', 'Address', 'Method', 'SellerG', 'Postcode'], axis=1)

In [46]:
# Propertycount was not fully evaluated in Exploration. Lets see if it holds anything significant
print(df['Price'].corr(df['Propertycount']))

-0.04215261472877342

In [47]:
# Remove Propertycount as well
df = df.drop(['Propertycount'], axis=1)

In [48]:
# In Exploration Phase it was seen that Rooms column is more accurate than Bedroom2
# There is no point in keeping two columns that will conflict with each other
df = df.drop(['Bedroom2'], axis=1)

In [49]:
# Created Duplicates. Drop those.
df = df.drop_duplicates()

In [50]:
# Lets see shape of data now
df.shape

(13579, 14)

### Dealing with Missing Values

In [51]:
# KNN Imputation is the most logical way of dealing with Missing Values and will give most accurate results
# CouncilArea is categorical so will be tricky. For that we can just set nulls to a "Missing String". Since only 10 percent not a huge deal
df['CouncilArea'] = df['CouncilArea'].fillna('MissingCouncil')

In [52]:
df.query("CouncilArea == 'MissingCouncil'").head(3)

,Rooms,Type,Price,Date,Distance,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname
7584,3,h,1270000.0,20/05/2017,10.7,1.0,3.0,724.0,NaN,NaN,MissingCouncil,-37.92910,145.02970,Southern Metropolitan
10797,3,h,526250.0,8/07/2017,12.0,1.0,1.0,308.0,NaN,NaN,MissingCouncil,-37.72828,145.03033,Northern Metropolitan
12213,4,h,1436000.0,3/09/2017,7.5,3.0,3.0,511.0,187.0,1922.0,MissingCouncil,-37.75788,144.90487,Western Metropolitan

Impute BuildingArea

In [53]:
from sklearn.impute import KNNImputer

# Select only the columns that will be used for imputation
columns_for_imputation = ['Rooms', 'Bathroom', 'BuildingArea']
temp_df = df[columns_for_imputation]

# Initialize the KNNImputer
imputer = KNNImputer(n_neighbors=3)

# Perform imputation using only 'Rooms' and 'Bathroom' for 'BuildingArea'
temp_df_imputed = pd.DataFrame(imputer.fit_transform(temp_df), columns=temp_df.columns)

# Replace the 'BuildingArea' column in the original dataframe with the imputed values
df['BuildingArea'] = temp_df_imputed['BuildingArea']

In [54]:
missing_proportions = df.isnull().sum() / df.shape[0]
missing_proportions = missing_proportions * 100
print(missing_proportions[missing_proportions > 0])

Car              0.456587
BuildingArea     0.007364
YearBuilt       39.583180
dtype: float64

In [55]:
# Interestingly after filling missing BuildingArea, correlation between it and Price (and all other features) went down
# Still have 1 missing BuildingArea: just delete it
df = df.dropna(subset=['BuildingArea'])

missing_proportions = df.isnull().sum() / df.shape[0]
missing_proportions = missing_proportions * 100
print(missing_proportions[missing_proportions > 0])

Car           0.456621
YearBuilt    39.586095
dtype: float64

Impute 'Car'

In [56]:
# Car was most correlated with Rooms and Landsize
from sklearn.impute import KNNImputer

# Select only the columns that will be used for imputation
columns_for_imputation = ['Rooms', 'Landsize', 'Car']
temp_df = df[columns_for_imputation]

# Initialize the KNNImputer
imputer = KNNImputer(n_neighbors=3)

# Perform imputation using only 'Rooms' and 'Landsize' for 'Car'
temp_df_imputed = pd.DataFrame(imputer.fit_transform(temp_df), columns=temp_df.columns)

# Replace the 'Car' column in the original dataframe with the imputed values
df['Car'] = temp_df_imputed['Car']

In [57]:
# Again, it seems KNN Imputation leaves 1 row that still missing value
df = df.dropna(subset=['Car'])

missing_proportions = df.isnull().sum() / df.shape[0]
missing_proportions = missing_proportions * 100
print(missing_proportions[missing_proportions > 0])

YearBuilt    39.589011
dtype: float64

Impute 'YearBuilt'

In [58]:
print(df['YearBuilt'].median())

1970.0

In [59]:
# YearBuilt isn't correlated with anything
# Just replace it with the most common and median value
df['YearBuilt'] = df['YearBuilt'].fillna(1970)

In [60]:
# No More Missing Values!
missing_proportions = df.isnull().sum() / df.shape[0]
missing_proportions = missing_proportions * 100
print(missing_proportions[missing_proportions > 0])

Series([], dtype: float64)

### Dealing with Outliers

To see the reasoning behind the decisions below please refer to the final report

In [61]:
df.shape

(13577, 14)

In [62]:
# Remove the YearBuilt Extreme outlier
df = df[df['YearBuilt'] != 1196]
df.shape

(13576, 14)

In [63]:
# Move lower range of Bathrooms (0) to 5th percentile and move rare high cases to sensible maximum
df.loc[df['Bathroom'] == 0, 'Bathroom'] = 1
df.loc[df['Bathroom'].isin([5, 6, 7, 8]), 'Bathroom'] = 4

In [64]:
# Prices column has a lot of variation. Not always clear if there is a data entry error
# Since the Price column is important we should remove the abnormaly high and low prices rather than distort reality by changing them
df = df[(df['Price'] >= 235000) & (df['Price'] <= 5000000)]

In [65]:
# BuildingArea
# Remove super abnormally high and lows 
df = df[(df['BuildingArea'] <= 6691)]
df = df[(df['BuildingArea'] >= 10)]

In [66]:
# Landsize
# Landsizes of 0 are ok, but extreme upper ends are outliers
# We can simply remove extreme values
df.query('Landsize > 4000').count()

Rooms           97
Type            97
Price           97
Date            97
Distance        97
Bathroom        97
Car             97
Landsize        97
BuildingArea    97
YearBuilt       97
CouncilArea     97
Lattitude       97
Longtitude      97
Regionname      97
dtype: int64

In [67]:
df = df[(df['Landsize'] <= 4000)]

In [68]:
df.shape

(13359, 14)

In [69]:
df.head(1)

,Rooms,Type,Price,Date,Distance,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname
0,2,h,1480000.0,3/12/2016,2.5,1.0,1.0,202.0,87.0,1970.0,Yarra,-37.7996,144.9984,Northern Metropolitan

### Feature Conversion

In [70]:
# Split Year to a season one-hot encoding and year sold feature

# Parse the Date column to datetime
df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')

df['YearSold'] = df['Date'].dt.year

def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:
        return 'Fall'
    
df['Season'] = df['Date'].dt.month.apply(get_season)

# One hot encode season
df = pd.concat([df, pd.get_dummies(df['Season'], prefix='Season')], axis=1)

df = df.drop(['Date', 'Season'], axis=1)

In [71]:
df.head(1)

,Rooms,Type,Price,Distance,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,YearSold,Season_Fall,Season_Spring,Season_Summer,Season_Winter
0,2,h,1480000.0,2.5,1.0,1.0,202.0,87.0,1970.0,Yarra,-37.7996,144.9984,Northern Metropolitan,2016,0,0,0,1

In [72]:
# Instead of having YearBuilt, we can have Age at time of selling
df['AgeAtSale'] = df['YearSold'] - df['YearBuilt']

# Drop the 'YearBuilt' column as it's no longer needed
data = df.drop(['YearBuilt'], axis=1)

# Show the resulting DataFrame to verify the changes
df.head(1)

,Rooms,Type,Price,Distance,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,YearSold,Season_Fall,Season_Spring,Season_Summer,Season_Winter,AgeAtSale
0,2,h,1480000.0,2.5,1.0,1.0,202.0,87.0,1970.0,Yarra,-37.7996,144.9984,Northern Metropolitan,2016,0,0,0,1,46.0

In [73]:
# One Hot Encode 'Type'
df = pd.concat([df, pd.get_dummies(df['Type'], prefix='Type')], axis=1)

df = df.drop('Type', axis=1)
df.head(1)

,Rooms,Price,Distance,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,...,Regionname,YearSold,Season_Fall,Season_Spring,Season_Summer,Season_Winter,AgeAtSale,Type_h,Type_t,Type_u
0,2,1480000.0,2.5,1.0,1.0,202.0,87.0,1970.0,Yarra,-37.7996,...,Northern Metropolitan,2016,0,0,0,1,46.0,1,0,0

In [74]:
# One Hot encode Council and Region

df = pd.concat([df, pd.get_dummies(df['CouncilArea'], prefix='Council')], axis=1)

df = df.drop('CouncilArea', axis=1)

df = pd.concat([df, pd.get_dummies(df['Regionname'], prefix='Region')], axis=1)

df = df.drop('Regionname', axis=1)

df.head(1)

,Rooms,Price,Distance,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,...,Council_Yarra,Council_Yarra Ranges,Region_Eastern Metropolitan,Region_Eastern Victoria,Region_Northern Metropolitan,Region_Northern Victoria,Region_South-Eastern Metropolitan,Region_Southern Metropolitan,Region_Western Metropolitan,Region_Western Victoria
0,2,1480000.0,2.5,1.0,1.0,202.0,87.0,1970.0,-37.7996,144.9984,...,1,0,0,0,1,0,0,0,0,0

In [75]:
df = df.drop('YearBuilt', axis=1)
df.head(1)

,Rooms,Price,Distance,Bathroom,Car,Landsize,BuildingArea,Lattitude,Longtitude,YearSold,...,Council_Yarra,Council_Yarra Ranges,Region_Eastern Metropolitan,Region_Eastern Victoria,Region_Northern Metropolitan,Region_Northern Victoria,Region_South-Eastern Metropolitan,Region_Southern Metropolitan,Region_Western Metropolitan,Region_Western Victoria
0,2,1480000.0,2.5,1.0,1.0,202.0,87.0,-37.7996,144.9984,2016,...,1,0,0,0,1,0,0,0,0,0

In [76]:
df.head(1)

,Rooms,Price,Distance,Bathroom,Car,Landsize,BuildingArea,Lattitude,Longtitude,YearSold,...,Council_Yarra,Council_Yarra Ranges,Region_Eastern Metropolitan,Region_Eastern Victoria,Region_Northern Metropolitan,Region_Northern Victoria,Region_South-Eastern Metropolitan,Region_Southern Metropolitan,Region_Western Metropolitan,Region_Western Victoria
0,2,1480000.0,2.5,1.0,1.0,202.0,87.0,-37.7996,144.9984,2016,...,1,0,0,0,1,0,0,0,0,0

### Feature Transformation

Decided to go with Normalization over Standardization

In [77]:
df.head(10).T

,0,1,2,3,4,5,6,7,8,9
Rooms,2.000000e+00,2.000000e+00,3.000000e+00,3.000000,4.000000e+00,2.0000,3.000000e+00,2.000000e+00,1.000000,2.000000e+00
Price,1.480000e+06,1.035000e+06,1.465000e+06,850000.000000,1.600000e+06,941000.0000,1.876000e+06,1.636000e+06,300000.000000,1.097000e+06
Distance,2.500000e+00,2.500000e+00,2.500000e+00,2.500000,2.500000e+00,2.5000,2.500000e+00,2.500000e+00,2.500000,2.500000e+00
Bathroom,1.000000e+00,1.000000e+00,2.000000e+00,2.000000,1.000000e+00,1.0000,2.000000e+00,1.000000e+00,1.000000,1.000000e+00
Car,1.000000e+00,0.000000e+00,0.000000e+00,1.000000,2.000000e+00,0.0000,0.000000e+00,2.000000e+00,1.000000,2.000000e+00
Landsize,2.020000e+02,1.560000e+02,1.340000e+02,94.000000,1.200000e+02,181.0000,2.450000e+02,2.560000e+02,0.000000,2.200000e+02
BuildingArea,8.700000e+01,7.900000e+01,1.500000e+02,183.333333,1.420000e+02,87.0000,2.100000e+02,1.070000e+02,44.666667,7.500000e+01
Lattitude,-3.779960e+01,-3.780790e+01,-3.780930e+01,-37.796900,-3.780720e+01,-37.8041,-3.780240e+01,-3.780600e+01,-37.800800,-3.780100e+01
Longtitude,1.449984e+02,1.449934e+02,1.449944e+02,144.996900,1.449941e+02,144.9953,1.449993e+02,1.449954e+02,144.997300,1.449989e+02
YearSold,2.016000e+03,2.016000e+03,2.017000e+03,2017.000000,2.016000e+03,2016.0000,2.016000e+03,2.016000e+03,2016.000000,2.016000e+03
Season_Fall,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,1.000000e+00,1.000000,1.000000e+00
Season_Spring,0.000000e+00,0.000000e+00,1.000000e+00,1.000000,0.000000e+00,1.0000,1.000000e+00,0.000000e+00,0.000000,0.000000e+00
Season_Summer,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,1.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Season_Winter,1.000000e+00,1.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
AgeAtSale,4.600000e+01,1.160000e+02,1.170000e+02,47.000000,2.000000e+00,46.0000,1.060000e+02,1.260000e+02,46.000000,1.160000e+02
Type_h,1.000000e+00,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.0000,1.000000e+00,1.000000e+00,0.000000,1.000000e+00
Type_t,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Type_u,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,1.000000,0.000000e+00
Council_Banyule,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Bayside,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Boroondara,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Brimbank,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Cardinia,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Casey,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Darebin,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Frankston,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Glen Eira,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Greater Dandenong,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Hobsons Bay,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Hume,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Kingston,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Knox,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Macedon Ranges,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Manningham,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Maribyrnong,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Maroondah,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Melbourne,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Melton,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_MissingCouncil,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Monash,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Moonee Valley,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Moorabool,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Moreland,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Nillumbik,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Port Phillip,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Stonnington,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Unavailable,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Whitehorse,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Whittlesea,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Wyndham,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Yarra,1.000000e+00,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.0000,1.000000e+00,1.000000e+00,1.000000,1.000000e+00
Council_Yarra Ranges,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Region_Eastern Metropolitan,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Region_Eastern Victoria,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Region_Northern Metropolitan,1.000000e+00,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.0000,1.000000e+00,1.000000e+00,1.000000,1.000000e+00
Region_Northern Victoria,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Region_South-Eastern Metropolitan,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Region_Southern Metropolitan,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Region_Western Metropolitan,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Region_Western Victoria,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00

In [78]:
from sklearn.preprocessing import MinMaxScaler
# We will normalize all numerical features aside from the Price Target Feature!

# Only need to normalize continuous/numeric Features (except price)
numerical_cols = ['Rooms', 'Distance', 'Bathroom', 'Car', 'Landsize', 'BuildingArea', 
                  'Lattitude', 'Longtitude', 'YearSold', 'AgeAtSale'] 

scaler = MinMaxScaler()

# Fit the scaler to your numerical feature data and transform it
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

In [79]:
df.head(10).T

,0,1,2,3,4,5,6,7,8,9
Rooms,1.111111e-01,1.111111e-01,2.222222e-01,0.222222,3.333333e-01,0.111111,2.222222e-01,1.111111e-01,0.000000,1.111111e-01
Price,1.480000e+06,1.035000e+06,1.465000e+06,850000.000000,1.600000e+06,941000.000000,1.876000e+06,1.636000e+06,300000.000000,1.097000e+06
Distance,5.274262e-02,5.274262e-02,5.274262e-02,0.052743,5.274262e-02,0.052743,5.274262e-02,5.274262e-02,0.052743,5.274262e-02
Bathroom,0.000000e+00,0.000000e+00,3.333333e-01,0.333333,0.000000e+00,0.000000,3.333333e-01,0.000000e+00,0.000000,0.000000e+00
Car,1.000000e-01,0.000000e+00,0.000000e+00,0.100000,2.000000e-01,0.000000,0.000000e+00,2.000000e-01,0.100000,2.000000e-01
Landsize,5.050000e-02,3.900000e-02,3.350000e-02,0.023500,3.000000e-02,0.045250,6.125000e-02,6.400000e-02,0.000000,5.500000e-02
BuildingArea,2.170237e-02,1.944758e-02,3.945885e-02,0.048854,3.720406e-02,0.021702,5.636979e-02,2.733935e-02,0.009771,1.832018e-02
Lattitude,4.896979e-01,4.788674e-01,4.770405e-01,0.493221,4.797808e-01,0.483826,4.860442e-01,4.813466e-01,0.488132,4.878711e-01
Longtitude,5.176513e-01,5.130831e-01,5.139967e-01,0.516281,5.137227e-01,0.514819,5.184735e-01,5.149104e-01,0.516646,5.181081e-01
YearSold,0.000000e+00,0.000000e+00,1.000000e+00,1.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Season_Fall,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,1.000000e+00,1.000000,1.000000e+00
Season_Spring,0.000000e+00,0.000000e+00,1.000000e+00,1.000000,0.000000e+00,1.000000,1.000000e+00,0.000000e+00,0.000000,0.000000e+00
Season_Summer,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,1.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Season_Winter,1.000000e+00,1.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
AgeAtSale,2.553191e-01,6.276596e-01,6.329787e-01,0.260638,2.127660e-02,0.255319,5.744681e-01,6.808511e-01,0.255319,6.276596e-01
Type_h,1.000000e+00,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.000000,1.000000e+00,1.000000e+00,0.000000,1.000000e+00
Type_t,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Type_u,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,1.000000,0.000000e+00
Council_Banyule,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Bayside,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Boroondara,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Brimbank,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Cardinia,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Casey,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Darebin,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Frankston,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Glen Eira,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Greater Dandenong,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Hobsons Bay,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Hume,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Kingston,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Knox,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Macedon Ranges,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Manningham,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Maribyrnong,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Maroondah,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Melbourne,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Melton,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_MissingCouncil,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Monash,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Moonee Valley,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Moorabool,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Moreland,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Nillumbik,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Port Phillip,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Stonnington,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Unavailable,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Whitehorse,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Whittlesea,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Wyndham,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Council_Yarra,1.000000e+00,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.000000,1.000000e+00,1.000000e+00,1.000000,1.000000e+00
Council_Yarra Ranges,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Region_Eastern Metropolitan,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Region_Eastern Victoria,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Region_Northern Metropolitan,1.000000e+00,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.000000,1.000000e+00,1.000000e+00,1.000000,1.000000e+00
Region_Northern Victoria,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Region_South-Eastern Metropolitan,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Region_Southern Metropolitan,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Region_Western Metropolitan,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
Region_Western Victoria,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00

Now we are done with all data cleaning and transformations and have a final dataset that will be used for predictions

In [80]:
df.to_csv('clean_data.csv', index=False)